<template>
  <main>
    <h1>使い方</h1>
    <div>
      <ol>
        <li>選考追加ページへ移動します。</li>
        <li>会社名の入力と選考方法を選択をして追加ボタンを押します。</li>
        <li>{作成中}</li>
      </ol>
    </div>
  </main>
</template>
